version: '3'
services:

  cli:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DB_NAME=cli_demo
      - MONGO_URL=mongodb://root:pass@db:27017
    command: /bin/bash
    entrypoint: ['/bin/bash', '/app/docker-compose-entrypoint.sh']
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  db_data:
